"""add academic directory requests

Revision ID: 054c5625a559
Revises: f51b16e1b4ea
Create Date: 2026-09-18 16:42:35.631006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054c5625a559'
down_revision = 'f51b16e1b4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('institution_type', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('official_website', sa.String(length=255), nullable=True),
    sa.Column('academic_unit_name', sa.String(length=200), nullable=True),
    sa.Column('academic_unit_type', sa.String(length=50), nullable=True),
    sa.Column('department_name', sa.String(length=200), nullable=True),
    sa.Column('programme_name', sa.String(length=200), nullable=True),
    sa.Column('award', sa.String(length=100), nullable=True),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('requester_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('review_started_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('directory_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directory_requests_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_requests_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directory_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_directory_requests_status'))
        batch_op.drop_index(batch_op.f('ix_directory_requests_request_type'))
        batch_op.drop_index(batch_op.f('ix_directory_requests_institution_id'))

    op.drop_table('directory_requests')
    # ### end Alembic commands ###
