"""add trusted data provenance foundation

Revision ID: 0f5b0cfdfb95
Revises: 8f5d74b88835
Create Date: 2026-09-30 19:16:06.478109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5b0cfdfb95'
down_revision = '8f5d74b88835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('authority_name', sa.String(length=200), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_source_type'), ['source_type'], unique=False)

    op.create_table('source_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('academic_unit_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('siwes_configuration_id', sa.Integer(), nullable=True),
    sa.Column('reference_url', sa.String(length=1000), nullable=True),
    sa.Column('reference_text', sa.String(length=500), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('checked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('\n            (\n                CASE WHEN institution_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN academic_unit_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN department_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN programme_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN siwes_configuration_id IS NOT NULL THEN 1 ELSE 0 END\n            ) = 1\n            ', name='ck_source_evidence_exactly_one_target'),
    sa.ForeignKeyConstraint(['academic_unit_id'], ['academic_units.id'], ),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.ForeignKeyConstraint(['siwes_configuration_id'], ['siwes_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_evidence_academic_unit_id'), ['academic_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_evidence_checked_by_user_id'), ['checked_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_evidence_claim_type'), ['claim_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_evidence_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_evidence_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_evidence_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_evidence_programme_id'), ['programme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_evidence_siwes_configuration_id'), ['siwes_configuration_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_evidence_siwes_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_source_evidence_programme_id'))
        batch_op.drop_index(batch_op.f('ix_source_evidence_institution_id'))
        batch_op.drop_index(batch_op.f('ix_source_evidence_department_id'))
        batch_op.drop_index(batch_op.f('ix_source_evidence_data_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_evidence_claim_type'))
        batch_op.drop_index(batch_op.f('ix_source_evidence_checked_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_source_evidence_academic_unit_id'))

    op.drop_table('source_evidence')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_source_type'))

    op.drop_table('data_sources')
    # ### end Alembic commands ###
