"""Add directory request clarification messages

Revision ID: 5d981f30a023
Revises: 054c5625a559
Create Date: 2026-09-27 11:26:24.479558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d981f30a023'
down_revision = '054c5625a559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_request_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directory_request_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['directory_request_id'], ['directory_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('directory_request_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directory_request_messages_author_type'), ['author_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_request_messages_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_request_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_directory_request_messages_directory_request_id'), ['directory_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory_request_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directory_request_messages_directory_request_id'))
        batch_op.drop_index(batch_op.f('ix_directory_request_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_directory_request_messages_author_user_id'))
        batch_op.drop_index(batch_op.f('ix_directory_request_messages_author_type'))

    op.drop_table('directory_request_messages')
    # ### end Alembic commands ###
