"""Add administrative role applications

Revision ID: 5e1d5ed7a72f
Revises: 025dbbc0c401
Create Date: 2026-09-12 15:57:46.413556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1d5ed7a72f'
down_revision = '025dbbc0c401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_role_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('academic_session', sa.String(length=100), nullable=True),
    sa.Column('official_position', sa.String(length=200), nullable=False),
    sa.Column('institutional_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('verification_method', sa.String(length=150), nullable=True),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('evidence_file_reference', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applicant_notes', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('review_started_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.ForeignKeyConstraint(['requested_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_applications_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_applications_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_applications_programme_id'), ['programme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_applications_requested_role_id'), ['requested_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_applications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_role_applications_status'))
        batch_op.drop_index(batch_op.f('ix_role_applications_requested_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_applications_programme_id'))
        batch_op.drop_index(batch_op.f('ix_role_applications_institution_id'))
        batch_op.drop_index(batch_op.f('ix_role_applications_department_id'))

    op.drop_table('role_applications')
    # ### end Alembic commands ###
