"""expand programme SIWES configuration

Revision ID: 84cc389dcf74
Revises: 5e1d5ed7a72f
Create Date: 2026-09-17 21:42:02.076652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cc389dcf74'
down_revision = '5e1d5ed7a72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_years', sa.Integer(), nullable=True))

    with op.batch_alter_table('siwes_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timing', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('verification_reference', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siwes_configurations', schema=None) as batch_op:
        batch_op.drop_column('verification_reference')
        batch_op.drop_column('timing')

    with op.batch_alter_table('programmes', schema=None) as batch_op:
        batch_op.drop_column('duration_years')

    # ### end Alembic commands ###
