"""Add academic directory source identity uniqueness

Revision ID: 8ff375472875
Revises: 5f733fe82e7c
Create Date: 2026-09-30 23:45:32.931440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff375472875'
down_revision = '5f733fe82e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_directory_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=300), nullable=False),
    sa.Column('normalized_alias', sa.String(length=300), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('academic_unit_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('\n            (\n                CASE WHEN institution_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN academic_unit_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN department_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN programme_id IS NOT NULL THEN 1 ELSE 0 END\n            ) = 1\n            ', name='ck_academic_directory_alias_exactly_one_target'),
    sa.ForeignKeyConstraint(['academic_unit_id'], ['academic_units.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_unit_id', 'normalized_alias', name='uq_academic_directory_alias_academic_unit'),
    sa.UniqueConstraint('department_id', 'normalized_alias', name='uq_academic_directory_alias_department'),
    sa.UniqueConstraint('institution_id', 'normalized_alias', name='uq_academic_directory_alias_institution'),
    sa.UniqueConstraint('programme_id', 'normalized_alias', name='uq_academic_directory_alias_programme')
    )
    with op.batch_alter_table('academic_directory_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_directory_aliases_academic_unit_id'), ['academic_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_directory_aliases_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_directory_aliases_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_directory_aliases_normalized_alias'), ['normalized_alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_directory_aliases_programme_id'), ['programme_id'], unique=False)

    op.create_table('academic_directory_source_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('external_identifier', sa.String(length=300), nullable=True),
    sa.Column('external_name', sa.String(length=300), nullable=True),
    sa.Column('normalized_external_name', sa.String(length=300), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('academic_unit_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('reference_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('\n            (\n                CASE WHEN institution_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN academic_unit_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN department_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN programme_id IS NOT NULL THEN 1 ELSE 0 END\n            ) = 1\n            ', name='ck_academic_directory_source_identity_exactly_one_target'),
    sa.CheckConstraint('\n            external_identifier IS NOT NULL\n            OR external_name IS NOT NULL\n            ', name='ck_academic_directory_source_identity_has_external_identity'),
    sa.ForeignKeyConstraint(['academic_unit_id'], ['academic_units.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_directory_source_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_directory_source_identities_academic_unit_id'), ['academic_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_directory_source_identities_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_directory_source_identities_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_directory_source_identities_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_directory_source_identities_normalized_external_name'), ['normalized_external_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_directory_source_identities_programme_id'), ['programme_id'], unique=False)
        batch_op.create_index('uq_academic_directory_source_identity_source_department_name', ['data_source_id', 'department_id', 'normalized_external_name'], unique=True, sqlite_where=sa.text("department_id IS NOT NULL AND normalized_external_name <> ''"))
        batch_op.create_index('uq_academic_directory_source_identity_source_identifier', ['data_source_id', 'external_identifier'], unique=True, sqlite_where=sa.text('external_identifier IS NOT NULL'))
        batch_op.create_index('uq_academic_directory_source_identity_source_institution_name', ['data_source_id', 'institution_id', 'normalized_external_name'], unique=True, sqlite_where=sa.text("institution_id IS NOT NULL AND normalized_external_name <> ''"))
        batch_op.create_index('uq_academic_directory_source_identity_source_programme_name', ['data_source_id', 'programme_id', 'normalized_external_name'], unique=True, sqlite_where=sa.text("programme_id IS NOT NULL AND normalized_external_name <> ''"))
        batch_op.create_index('uq_academic_directory_source_identity_source_unit_name', ['data_source_id', 'academic_unit_id', 'normalized_external_name'], unique=True, sqlite_where=sa.text("academic_unit_id IS NOT NULL AND normalized_external_name <> ''"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_directory_source_identities', schema=None) as batch_op:
        batch_op.drop_index('uq_academic_directory_source_identity_source_unit_name', sqlite_where=sa.text("academic_unit_id IS NOT NULL AND normalized_external_name <> ''"))
        batch_op.drop_index('uq_academic_directory_source_identity_source_programme_name', sqlite_where=sa.text("programme_id IS NOT NULL AND normalized_external_name <> ''"))
        batch_op.drop_index('uq_academic_directory_source_identity_source_institution_name', sqlite_where=sa.text("institution_id IS NOT NULL AND normalized_external_name <> ''"))
        batch_op.drop_index('uq_academic_directory_source_identity_source_identifier', sqlite_where=sa.text('external_identifier IS NOT NULL'))
        batch_op.drop_index('uq_academic_directory_source_identity_source_department_name', sqlite_where=sa.text("department_id IS NOT NULL AND normalized_external_name <> ''"))
        batch_op.drop_index(batch_op.f('ix_academic_directory_source_identities_programme_id'))
        batch_op.drop_index(batch_op.f('ix_academic_directory_source_identities_normalized_external_name'))
        batch_op.drop_index(batch_op.f('ix_academic_directory_source_identities_institution_id'))
        batch_op.drop_index(batch_op.f('ix_academic_directory_source_identities_department_id'))
        batch_op.drop_index(batch_op.f('ix_academic_directory_source_identities_data_source_id'))
        batch_op.drop_index(batch_op.f('ix_academic_directory_source_identities_academic_unit_id'))

    op.drop_table('academic_directory_source_identities')
    with op.batch_alter_table('academic_directory_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_directory_aliases_programme_id'))
        batch_op.drop_index(batch_op.f('ix_academic_directory_aliases_normalized_alias'))
        batch_op.drop_index(batch_op.f('ix_academic_directory_aliases_institution_id'))
        batch_op.drop_index(batch_op.f('ix_academic_directory_aliases_department_id'))
        batch_op.drop_index(batch_op.f('ix_academic_directory_aliases_academic_unit_id'))

    op.drop_table('academic_directory_aliases')
    # ### end Alembic commands ###
