"""add student level and siwes session

Revision ID: e0b94e69a3f9
Revises: c5138ca49a20
Create Date: 2026-09-11 20:49:10.462801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b94e69a3f9'
down_revision = 'c5138ca49a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('siwes_session', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('siwes_session')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
