"""Add city to institution directory

Revision ID: f51b16e1b4ea
Revises: 84cc389dcf74
Create Date: 2026-09-18 05:08:39.798553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51b16e1b4ea'
down_revision = '84cc389dcf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
